# Generated by Django 3.0 on 2019-12-05 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_auto_20191204_2055'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name',)},
        ),
    ]
