# Generated by Django 3.0 on 2019-12-06 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0004_auto_20191205_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcard.Category'),
        ),
    ]
