# Generated by Django 3.0 on 2019-12-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0005_auto_20191206_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='question',
            field=models.CharField(max_length=150),
        ),
    ]
