// CARDS
export const ADD_CARD = 'ADD_CARD';
export const CARD_UPDATED = 'CARD_UPDATED';
export const SET_CARDS = 'SET_CARDS';
export const CARD_FETCHED = 'CARD_FETCHED';
export const CARD_DELETED = 'CARD_DELETED';

// CATEGORY
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const CATEGORY_UPDATED = 'CATEGORY_UPDATED';
export const CATEGORY_DELETED = 'CATEGORY_DELETED';
